AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Documentation Hosting

Resources:
  BucketProduction:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: docs.maiar.exchange
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  BucketProductionPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketProduction
      PolicyDocument:
        Id: bucket-policy
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::docs.maiar.exchange/*"

  CloudFrontProduction:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ErrorCachingMinTTL: 60
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        Aliases:
          - docs.maiar.exchange
        Origins:
          - Id: s3-static-site
            DomainName: docs.maiar.exchange.s3-website.us-east-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:777241893292:certificate/125b7a46-32b0-4bb1-98af-db25ef0c3542"
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          MaxTTL: 60
          DefaultTTL: 60
          ForwardedValues:
            QueryString: false
            Headers:
              - CloudFront-Viewer-Country
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: s3-static-site
